sudo: required

language: generic

services:
    - docker
before_install:
    - docker build  -t krishnamaheshteja/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true krishnamaheshteja/react-test npm run test

after_success:
    - docker build -t krishnamaheshteja/multi-client ./client
    - docker build -t krishnamaheshteja/multi-nginx ./nginx
    - docker build -t krishnamaheshteja/multi-server ./server
    - docker build -t krishnamaheshteja/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push krishnamaheshteja/multi-client
    - docker push krishnamaheshteja/multi-nginx
    - docker push krishnamaheshteja/multi-server
    - docker push krishnamaheshteja/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-855529103475"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY